CREATE SCHEMA "management";

CREATE SCHEMA "operations";

CREATE TABLE "management"."roles" (
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("name")
);

CREATE TABLE "management"."users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "role" TEXT NOT NULL
);

CREATE TABLE "operations"."polls" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP,
    "status" TEXT NOT NULL DEFAULT 'open'
);

CREATE TABLE "operations"."questions" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "poll_id" INT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT
);

CREATE TABLE "operations"."answers" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "question_id" INT NOT NULL,
    "title" TEXT NOT NULL
);

CREATE TABLE "operations"."voters" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "poll_id" INT NOT NULL,
    "name" TEXT NOT NULL
);

CREATE TABLE "operations"."uniquecodes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "voter_id" INT NOT NULL,
    "code" TEXT NOT NULL
);

CREATE TABLE "operations"."votes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "voter_id" INT NOT NULL,
    "answer_id" INT NOT NULL,
    "question_id" INT NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP
);

ALTER TABLE "management"."users" ADD FOREIGN KEY ("role") REFERENCES "management"."roles" ("name") ON DELETE RESTRICT;

ALTER TABLE "operations"."polls" ADD FOREIGN KEY ("user_id") REFERENCES "management"."users" ("id") ON DELETE CASCADE;

ALTER TABLE "operations"."questions" ADD FOREIGN KEY ("poll_id") REFERENCES "operations"."polls" ("id") ON DELETE CASCADE;

ALTER TABLE "operations"."answers" ADD FOREIGN KEY ("question_id") REFERENCES "operations"."questions" ("id") ON DELETE CASCADE;

ALTER TABLE "operations"."voters" ADD FOREIGN KEY ("poll_id") REFERENCES "operations"."polls" ("id") ON DELETE CASCADE;

ALTER TABLE "operations"."uniquecodes" ADD FOREIGN KEY ("voter_id") REFERENCES "operations"."voters" ("id") ON DELETE CASCADE;

INSERT INTO "management"."roles" ("name") VALUES ('admin');
INSERT INTO "management"."roles" ("name") VALUES ('user');
