CREATE SCHEMA "management";

CREATE SCHEMA "operations";

CREATE TABLE "management"."roles" (
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("name")
);

CREATE TABLE "management"."users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "role" TEXT NOT NULL
);


CREATE TABLE "management"."nominees" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL
);

CREATE TABLE "management"."categories" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "nominees" TEXT[] NOT NULL
);

CREATE TABLE "management"."categories_nominees" (
    "category_id" INT NOT NULL,
    "nominee_id" INT NOT NULL
);

CREATE TABLE "management"."uniquecodes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" VARCHAR(255) NOT NULL,
    "used" BOOLEAN NOT NULL,
    "category_id" INT NOT NULL,
    "nominee_id" INT NOT NULL
);

CREATE TABLE "operations"."votes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uniquecode_id" INT NOT NULL,
    "nominee_id" INT NOT NULL,
    "category_id" INT NOT NULL
);

CREATE TABLE "operations"."voters" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "poll_id" INT NOT NULL,
    "name" TEXT NOT NULL
);

CREATE TABLE "operations"."uniquecodes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "voter_id" INT NOT NULL,
    "code" VARCHAR(255) NOT NULL,
    "used" BOOLEAN NOT NULL DEFAULT false
);

--ALTER TABLE "operations.uniquecodes" ADD CONSTRAINT "operations_uniquecodes_fk_voter" FOREIGN KEY ("voter_id") REFERENCES "operations.voters" ("id") ON DELETE CASCADE;

--ALTER TABLE "operations"."voters" ADD CONSTRAINT "operations_voters_fk_poll" FOREIGN KEY ("poll_id") REFERENCES "operations"."polls" ("id") ON DELETE CASCADE;

