CREATE SCHEMA "management";

CREATE SCHEMA "operations";

CREATE TABLE "management"."roles" (
    "name" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("name")
);

CREATE TABLE "management"."users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "role" TEXT NOT NULL
);


CREATE TABLE "management"."nominees" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL
);

CREATE TABLE "management"."categories" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "nominees" TEXT[] NOT NULL
);

CREATE TABLE "management"."categories_nominees" (
    "category_id" INT NOT NULL,
    "nominee_id" INT NOT NULL
);

CREATE TABLE "management"."uniquecodes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" VARCHAR(255) NOT NULL,
    "used" BOOLEAN NOT NULL,
    "category_id" INT NOT NULL,
    "nominee_id" INT NOT NULL
);

CREATE TABLE "operations"."votes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uniquecode_id" INT NOT NULL,
    "nominee_id" INT NOT NULL,
    "category_id" INT NOT NULL
);

ALTER TABLE "management"."users" ADD CONSTRAINT "oscars_users_role_fk" FOREIGN KEY ("role") REFERENCES "management"."roles" ("name") ON DELETE RESTRICT;
ALTER TABLE "management"."categories_nominees" ADD CONSTRAINT "oscars_categories_nominees_category_pk" PRIMARY KEY ("category_id", "nominee_id");
ALTER TABLE "management"."categories_nominees" ADD CONSTRAINT "oscars_categories_nominees_category_fk" FOREIGN KEY ("category_id") REFERENCES "management"."categories" ("id") ON DELETE CASCADE;
ALTER TABLE "management"."categories_nominees" ADD CONSTRAINT "oscars_categories_nominees_nominee_fk" FOREIGN KEY ("nominee_id") REFERENCES "management"."nominees" ("id") ON DELETE CASCADE;
ALTER TABLE "management"."uniquecodes" ADD CONSTRAINT "oscars_uniquecodes_nominee_fk" FOREIGN KEY ("nominee_id") REFERENCES "management"."nominees" ("id") ON DELETE CASCADE;
ALTER TABLE "management"."uniquecodes" ADD CONSTRAINT "oscars_uniquecodes_category_fk" FOREIGN KEY ("category_id") REFERENCES "management"."categories" ("id") ON DELETE CASCADE;
ALTER TABLE "management"."uniquecodes" ADD CONSTRAINT "oscars_uniquecodes_u_code" UNIQUE ("code");
ALTER TABLE "management"."uniquecodes" ADD CONSTRAINT "oscars_uniquecodes_u_nominee_category" UNIQUE ("category_id", "nominee_id");
ALTER TABLE "operations"."votes" ADD CONSTRAINT "oscars_votes_uniquecode_fk" FOREIGN KEY ("uniquecode_id") REFERENCES "management"."uniquecodes" ("id") ON DELETE CASCADE;
ALTER TABLE "operations"."votes" ADD CONSTRAINT "oscars_votes_nominee_fk" FOREIGN KEY ("nominee_id") REFERENCES "management"."nominees" ("id") ON DELETE CASCADE;
ALTER TABLE "operations"."votes" ADD CONSTRAINT "oscars_votes_category_fk" FOREIGN KEY ("category_id") REFERENCES "management"."categories" ("id") ON DELETE CASCADE;
